'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("IMSS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _13592621542332() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_13592621542332", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Autorun_Button_Icon_27x23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Autorun_Button_Icon_27x23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Back_Icon_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Back_Icon_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Block_USB_PORTS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Block_USB_PORTS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Blue_Arrow_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Blue_Arrow_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Blue_Arrow_Up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Blue_Arrow_Up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_ClearQFiles_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_ClearQFiles_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Delete_Icon_32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Delete_Icon_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_DeleteButton_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_DeleteButton_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_DeviceImmunizer_Icon_37x27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_DeviceImmunizer_Icon_37x27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_EncryptionProcess_Icon_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_EncryptionProcess_Icon_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Error_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Error_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_ErrorExtracting_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_ErrorExtracting_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_FindProcess_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_FindProcess_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Fix_Tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Fix_Tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_G_Home_Status_Icon_27x37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_G_Home_Status_Icon_27x37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Genral_Protection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Genral_Protection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_GreenCheck_Icon_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_GreenCheck_Icon_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_GreenCheckMark_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_GreenCheckMark_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Info_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Info_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Info_ToolTip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Info_ToolTip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_LoadimgGif_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_LoadimgGif_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_LockedItems_icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_LockedItems_icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Log_Icon_24x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Log_Icon_24x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Main_G_Home_Icon_27x37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Main_G_Home_Icon_27x37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_MainSettings_SettingsButton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_MainSettings_SettingsButton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_MainVar_Icon_28x25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_MainVar_Icon_28x25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_MainWindow_Buttons_BG_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_MainWindow_Buttons_BG_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_MainWindowHideMe_Nutton_Icon_40x20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_MainWindowHideMe_Nutton_Icon_40x20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_ModeSettingsIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_ModeSettingsIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Monitors_Buttons_Icon_27x37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Monitors_Buttons_Icon_27x37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_OpenFileLocation_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_OpenFileLocation_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Pic_Fix_Tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Pic_Fix_Tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Pr_Off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Pr_Off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_ProcessesManager_Loading_Icon_400x50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_ProcessesManager_Loading_Icon_400x50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_ProcessingFile_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_ProcessingFile_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Properties_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Properties_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_PROTCION_SETTINGS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_PROTCION_SETTINGS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Q_Clear_Log_Icon_34x34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Q_Clear_Log_Icon_34x34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Quarantine_Button_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Quarantine_Button_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_QuarantineRoom_Icon_24x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_QuarantineRoom_Icon_24x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Refresh_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Refresh_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_RestoreTo_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_RestoreTo_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_SaveSettings_20x20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_SaveSettings_20x20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Scan_USB_Button_Icon_37x37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Scan_USB_Button_Icon_37x37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_ScanOnline_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_ScanOnline_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_SecuritySettings_Icon_24x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_SecuritySettings_Icon_24x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_SelectedLang_Icon_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_SelectedLang_Icon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Set_Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Set_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Settings_Slide_Back_Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Settings_Slide_Back_Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Tools_Bar_Icon_28x25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Tools_Bar_Icon_28x25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Tools_Button_icon_27x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Tools_Button_icon_27x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Tools_Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Tools_Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_UAC_Icon_40x30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_UAC_Icon_40x30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_UnBlock_USB_PORTS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_UnBlock_USB_PORTS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_UnderScoureMini_Icon_10x2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_UnderScoureMini_Icon_10x2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_Update_Bar_Icon_28x25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_Update_Bar_Icon_28x25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_UpdatePicSettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_UpdatePicSettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_UpdateSettings_24x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_UpdateSettings_24x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_USB_Configure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_USB_Configure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_USB_Format() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_USB_Format", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_USB_Scan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_USB_Scan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _IMSS_USB_Status() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_IMSS_USB_Status", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMSS_Main_Logo_Title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMSS_Main_Logo_Title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMSS_Main_Logo_Title_OnMouseOver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMSS_Main_Logo_Title_OnMouseOver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMSS_Monitors_BackGroundOnMuseOver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMSS_Monitors_BackGroundOnMuseOver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property IMSS_SERVER() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("IMSS_SERVER", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMSS_StartButtonOnMouseOver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMSS_StartButtonOnMouseOver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMSS_StartButtonOnMouseStand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMSS_StartButtonOnMouseStand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMSS_System_Mointor_Logo_Title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMSS_System_Mointor_Logo_Title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IMSSBlueArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMSSBlueArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to D6099259B078D226664C8BB27932EFB3
        '''44D88612FEA8A8F36DE82E1278ABB02F
        '''6CE6F415D8475545BE5BA114F208B0FF
        '''E4968EF99266DF7C9A1F0637D2389DAB
        '''4648E0A2FBFE469D8155F067DB0FB398
        '''40782BC57729C59BAA4CFD3A0D698437
        '''46B255D40ED4C9BEBA659C6075036226
        '''f0757e2587b6eb2845fdeb1a2eba6599
        '''426a5ce4f7c5f2bc010b85fa2ea946db
        '''8582021b1a85b214b0c031f58bc827a
        '''d84df9d063eb5b385ed04a4865dba81c
        '''9800aae15fecd97b2cd226d4bf543dcd
        '''969bd50272ba51ba75ea2f1396da22f8
        '''78c6ffb0f2250c22569abc5ea157cd3b
        '''0b0a8ec0bff9934f0e6c48548cfec4a3
        '''713 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property IMSSREDCODES() As String
            Get
                Return ResourceManager.GetString("IMSSREDCODES", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
